---
general:
  buildTool: "npm"
service:
  buildToolVersion: "N18"
  stages:
stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: false
  Additional Unit Tests:
    npmExecuteScripts: false
  Acceptance:
    npmExecuteEndToEndTests: false
    cloudFoundryDeploy: false
  Compliance:
    sonarExecuteScan: false
steps:
  artifactPrepareVersion:
    versioningType: "cloud_noTag"
  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"
